version: "3.8"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - PASSWORD=joshbodnar
      - SUDO_PASSWORD=joshbodnar
    volumes:
      - "$PWD/config:/config"
    ports:
      - 9000:8443

  server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "$PWD/config/workspace:/usr/share/nginx/html/"
